# Generated by Django 4.0.4 on 2022-05-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(upload_to='image_person', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(max_length=30, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
    ]
